swagger: "2.0"
info:
  title: "Dukedoms Card Service Api"
  version: "0.1.0"

paths:
  /setCardList:
    post:
      summary: set the card list for a given game id
      x-swagger-router-controller: list_operations
      operationId: set_card_list
      tags:
        - listOperations
      consumes:
        - application/json
      parameters:
        - in: body
          name: setCardListRequest
          description: request to set a given game's card list
          schema:
            $ref: '#/definitions/SetCardListRequest'
      responses:
        200:
          description: game card list set successfully

  /getCardList/{gameId}:
    get:
      summary: get the card list for a given game
      x-swagger-router-controller: list_operations
      operationId: get_card_list
      tags:
        - listOperations
      parameters:
        - in: path
          name: gameId
          type: integer
          required: true
          description: id of the game for which to fetch card list
      responses:
        200:
          description: game card list found successfully
        404:
          description: no game found with that id

  /getCardCatalog:
    get:
      summary: return list of all possible game cards
      x-swagger-router-controller: card_info
      operationId: get_card_catalog
      tags:
        - cardInfo
    responses:
      200:
        description: card list returned successfully

  /getCards/{cardIds}:
    get:
      summary: get info for specified cards
      x-swagger-router-controller: card_info
      operationId: get_cards
      tags:
        - cardInfo
      parameters:
        - in: path
          name: cardIds
          type: array
          items:
            type: integer
          required: true
          description: array of card ids for which to fetch info
      responses:
        200:
          description: card info fetched successfully
          schema:
            $ref: '#/definitions/RequestedCardInfo'
        404:
          description: unable to find following card ids
          schema:
            type: array
            items:
              type: integer

definitions:
  SetCardListRequest:
    type: object
    properties:
      gameId:
        type: integer
      victoryCards:
        type: array
        items:
          type: integer
      treasureCards:
        type: array
        items:
          type: integer
      actionCards:
        type: array
        items:
          type: integer
